### ISSUE TITLE
Errcode x10008 when trying to generate the summary

### ISSUE THREAD

**Issue by fabiovin70** [qayyumabro/Youtube-Transcript-AI-Summary#1]
Everytime I try to generate a summary I got this error:

Request failed, please try again.
Errcode: x10008

Clicking "retry" doesn't solve.

**Comment by quesada** [comment]
Can reproduce

**Comment by fabiovin70** [comment]
For me it happens only when the LONG button is selected

**Comment by qayyumabro** [comment]
Hi, which browser, and can you confirm you have a balance in your account and API key is copied correctly?

**Comment by fabiovin70** [comment]
![image](https://user-images.githubusercontent.com/35801287/231465795-94852df9-7c6d-40d1-8cdf-2ebb9c116a74.png)
without the LONG button selected, the summary is often truncated.

![image](https://user-images.githubusercontent.com/35801287/231466027-cf293a0c-dd6e-4d57-b78e-d37b96258772.png)
with the LONG button selected, I get this error.

This behaviour happens only in Firefox, both in Windows and in Ubuntu.
In Chrome instead it's working fine.

In Firefox I supplied all the required permissions:
![image](https://user-images.githubusercontent.com/35801287/231469071-68c9e72e-dd9d-45b5-b908-766cb12e7e59.png)

The balance in my account is okay.
I have only regular chatgpt and not chatgpt+ but I believe this is not a problem since in Chrome it is working.

Are these settings correct?
![image](https://user-images.githubusercontent.com/35801287/231469873-51d3a540-68b7-4128-868f-da8796d25c4a.png)

**Comment by qayyumabro** [comment]
Fixed in the 1.0.7 version on Mozilla. It should be live in a few hours.
