### ISSUE TITLE
Errcode: x10006

### ISSUE THREAD

**Issue by Tip2050** [qayyumabro/Youtube-Transcript-AI-Summary#11]
Hello,
I am user of the pro version and have received the Errcode: x10006 when I request Generate Summary.
Thanks for support

**Comment by qayyumabro** [comment]
Hi send settings screenshots at m.qayyum @live.com.

Regards
________________________________
From: Tip2050 ***@***.***>
Sent: Thursday, January 4, 2024 4:36 PM
To: qayyumabro/Youtube-Transcript-AI-Summary ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [qayyumabro/Youtube-Transcript-AI-Summary] Errcode: x10006 (Issue #11)


Hello,
I am user of the pro version and have received the Errcode: x10006 when I request Generate Summary.
Thanks for support
