### ISSUE TITLE
Hi, you need advance balance in your openai account.

### ISSUE THREAD

**Issue by Hussameosman** [qayyumabro/Youtube-Transcript-AI-Summary#13]
Hi, you need advance balance in your openai account.

_Originally posted by @qayyumabro in https://github.com/qayyumabro/Youtube-Transcript-AI-Summary/issues/10#issuecomment-1712002822_

**Comment by Hussameosman** [comment]
What is advance balance, and how do I get it please?

**Comment by qayyumabro** [comment]
https://platform.openai.com/usage

https://imghostr.com/929d36_m6x
