### ISSUE TITLE
Dang, no transcript is available for this video.

### ISSUE THREAD

**Issue by Hussameosman** [qayyumabro/Youtube-Transcript-AI-Summary#14]
Dang, no transcript is available for this video.

**Comment by qayyumabro** [comment]
Can you share the video link?

**Comment by Hussameosman** [comment]
https://www.youtube.com/live/qPt0yNNoiAI?si=vl6YfiKyD8HrUH66

**Comment by Hussameosman** [comment]
It started to work now
