### ISSUE TITLE
No transcription or summary from YouTube

### ISSUE THREAD

**Issue by lowbuffa** [qayyumabro/Youtube-Transcript-AI-Summary#15]
I just added the AI Summary extension for Bing, and it the first YouTube video I tried to have it summarized returned an error message of 10006

**Comment by qayyumabro** [comment]
Hi, can you please verify you have balance in your openai api account?

**Comment by lowbuffa** [comment]
If by “balance” you mean, “have I put money into it?”, I have not. When I downloaded it, there was no suggestion that it had a cost. If it has a cost, I won’t be using it. ThanksOn May 31, 2024, at 12:19 PM, qayyumabro ***@***.***> wrote:﻿
Hi, can you please verify you have balance in your openai api account?
