### ISSUE TITLE
Errcode: x10001

### ISSUE THREAD

**Issue by mjeragh** [qayyumabro/Youtube-Transcript-AI-Summary#3]
loading this youtube video  https://www.youtube.com/watch?v=PFDu9oVAE-g

I get the following error 
Errcode: x10001 

<img width="380" alt="Screenshot 2023-04-16 at 11 15 24 PM" src="https://user-images.githubusercontent.com/2122022/232339674-a82c7e92-b33f-4f86-8377-2e5b3010d364.png">

Please Help

**Comment by qayyumabro** [comment]
Hi, looks like openai api key is not provided, or balance issue. The video summary loads fine on Chrome.

**Comment by mjeragh** [comment]
Can you please elaborate further, I copied the key from openaI, I have the chatPlus subscription
<img width="493" alt="Screenshot 2023-04-17 at 12 11 02 AM" src="https://user-images.githubusercontent.com/2122022/232342379-7be1a837-4dd9-4066-a62a-d9f95c5e66c3.png">

Thank you in advance

**Comment by qayyumabro** [comment]
API usage is separate from ChatGPT subscription:
https://platform.openai.com/account/billing/overview



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by mjeragh** [comment]
You were right. Now it working on MS Edge.

Thank you
