### ISSUE TITLE
Request failed, please try again. Errcode: x10001

### ISSUE THREAD

**Issue by Mossie1-stack** [qayyumabro/Youtube-Transcript-AI-Summary#9]

**Comment by amashraqui** [comment]
I am getting this error message  Request failed, please try again. Errcode: x10001

**Comment by amashraqui** [comment]
Request failed, please try again. Errcode: x10001

**Comment by qayyumabro** [comment]
https://github.com/qayyumabro/Youtube-Transcript-AI-Summary/issues/3#issuecomment-1510489801
